// Generated immutable identity records; these do not instantiate framework agents.
export const mintOpalAgents = [
  {
    "swarm_index": 65,
    "identity_code": "DSW-MO-065",
    "agent_id": "agent-adk",
    "display_name": "Mint Seed",
    "domain": "ADK",
    "role": "Agent construction",
    "perspective": "Compose agents, tools, sessions and workflow building blocks.",
    "group": "frameworks-and-interaction",
    "palette_token": "DSW-MO-P50",
    "fallback_hex": "#60D9C2",
    "material_kind": "opal-splatter",
    "material_strength": 0.55555556
  },
  {
    "swarm_index": 66,
    "identity_code": "DSW-MO-066",
    "agent_id": "agent-ag2",
    "display_name": "Mint Council",
    "domain": "AG2",
    "role": "Multi-agent dialogue",
    "perspective": "Design participant roles, turn-taking, delegation and conversation handoffs.",
    "group": "frameworks-and-interaction",
    "palette_token": "DSW-MO-P51",
    "fallback_hex": "#5DDCC2",
    "material_kind": "opal-splatter",
    "material_strength": 0.44444444
  },
  {
    "swarm_index": 67,
    "identity_code": "DSW-MO-067",
    "agent_id": "agent-agno",
    "display_name": "Mint Grove",
    "domain": "Agno",
    "role": "Agent teams",
    "perspective": "Organize agent teams, knowledge, memory and tools into coherent services.",
    "group": "frameworks-and-interaction",
    "palette_token": "DSW-MO-P52",
    "fallback_hex": "#5ADEC2",
    "material_kind": "opal-splatter",
    "material_strength": 0.33333333
  },
  {
    "swarm_index": 68,
    "identity_code": "DSW-MO-068",
    "agent_id": "agent-bot",
    "display_name": "Mint Relay",
    "domain": "Conversational bots",
    "role": "Channel interaction",
    "perspective": "Route conversation events, maintain bot state and hand off to specialists.",
    "group": "frameworks-and-interaction",
    "palette_token": "DSW-MO-P53",
    "fallback_hex": "#57E1C2",
    "material_kind": "opal-splatter",
    "material_strength": 0.22222222
  },
  {
    "swarm_index": 69,
    "identity_code": "DSW-MO-069",
    "agent_id": "agent-claude-sdk",
    "display_name": "Mint Forge",
    "domain": "Claude Agent SDK",
    "role": "Coding workflows",
    "perspective": "Plan code changes, scoped tool execution and reviewable engineering outputs.",
    "group": "frameworks-and-interaction",
    "palette_token": "DSW-MO-P54",
    "fallback_hex": "#54E3C2",
    "material_kind": "opal-splatter",
    "material_strength": 0.11111111
  },
  {
    "swarm_index": 70,
    "identity_code": "DSW-MO-070",
    "agent_id": "agent-computer",
    "display_name": "Mint Pilot",
    "domain": "Computer interaction",
    "role": "Desktop operation",
    "perspective": "Map visible interface state to bounded, observable computer actions.",
    "group": "frameworks-and-interaction",
    "palette_token": "DSW-MO-P55",
    "fallback_hex": "#50E6C2",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 71,
    "identity_code": "DSW-MO-071",
    "agent_id": "agent-crewai",
    "display_name": "Mint Crew",
    "domain": "CrewAI",
    "role": "Role-based collaboration",
    "perspective": "Coordinate role-based crews, task delegation and event-driven flows.",
    "group": "frameworks-and-interaction",
    "palette_token": "DSW-MO-P56",
    "fallback_hex": "#6BE9C9",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 72,
    "identity_code": "DSW-MO-072",
    "agent_id": "agent-langgraph",
    "display_name": "Mint Branch",
    "domain": "LangGraph",
    "role": "Stateful graphs",
    "perspective": "Model branching execution, graph state, checkpoints and recovery paths.",
    "group": "frameworks-and-interaction",
    "palette_token": "DSW-MO-P57",
    "fallback_hex": "#81EBCF",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 73,
    "identity_code": "DSW-MO-073",
    "agent_id": "agent-langgraph-agui",
    "display_name": "Mint Stream",
    "domain": "LangGraph + AG-UI",
    "role": "Agent-user interaction",
    "perspective": "Connect graph execution with event-driven UI state and human interaction.",
    "group": "frameworks-and-interaction",
    "palette_token": "DSW-MO-P58",
    "fallback_hex": "#95EED6",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 74,
    "identity_code": "DSW-MO-074",
    "agent_id": "agent-langroid",
    "display_name": "Mint Dialog",
    "domain": "Langroid",
    "role": "Message-oriented agents",
    "perspective": "Compose message-driven agents, tool exchange and collaborative tasks.",
    "group": "frameworks-and-interaction",
    "palette_token": "DSW-MO-P59",
    "fallback_hex": "#A6F0DD",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 75,
    "identity_code": "DSW-MO-075",
    "agent_id": "agent-llamaindex",
    "display_name": "Mint Index",
    "domain": "LlamaIndex",
    "role": "Document agents",
    "perspective": "Organize retrieval, document reasoning and event-driven data workflows.",
    "group": "frameworks-and-interaction",
    "palette_token": "DSW-MO-P60",
    "fallback_hex": "#B7F3E4",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 76,
    "identity_code": "DSW-MO-076",
    "agent_id": "agent-mastra",
    "display_name": "Mint Flow",
    "domain": "Mastra",
    "role": "TypeScript agents",
    "perspective": "Compose TypeScript agents, workflows and application-facing tools.",
    "group": "frameworks-and-interaction",
    "palette_token": "DSW-MO-P61",
    "fallback_hex": "#C7F5EA",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 77,
    "identity_code": "DSW-MO-077",
    "agent_id": "agent-microsoft",
    "display_name": "Mint Mesh",
    "domain": "Microsoft Agent Framework",
    "role": "Enterprise agents",
    "perspective": "Coordinate agents, workflows, sessions, tool integration and enterprise context.",
    "group": "frameworks-and-interaction",
    "palette_token": "DSW-MO-P62",
    "fallback_hex": "#D6F7F1",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 78,
    "identity_code": "DSW-MO-078",
    "agent_id": "agent-pydantic-ai",
    "display_name": "Mint Contract",
    "domain": "Pydantic AI",
    "role": "Typed agent contracts",
    "perspective": "Validate structured inputs and outputs, dependencies and typed tool boundaries.",
    "group": "frameworks-and-interaction",
    "palette_token": "DSW-MO-P63",
    "fallback_hex": "#E5F9F8",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 79,
    "identity_code": "DSW-MO-079",
    "agent_id": "agent-strands",
    "display_name": "Mint Thread",
    "domain": "Strands Agents",
    "role": "Model-driven tool loops",
    "perspective": "Compose tool-using agents and cooperative execution patterns.",
    "group": "frameworks-and-interaction",
    "palette_token": "DSW-MO-P64",
    "fallback_hex": "#F4FBFF",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 80,
    "identity_code": "DSW-MO-080",
    "agent_id": "agent-mcp",
    "display_name": "Mint Socket",
    "domain": "Tool connectivity",
    "role": "Protocol engineering",
    "perspective": "Expose scoped tools, resources and interface contracts.",
    "group": "integration",
    "palette_token": "DSW-MO-P01",
    "fallback_hex": "#00CFFF",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 81,
    "identity_code": "DSW-MO-081",
    "agent_id": "agent-a2a",
    "display_name": "Mint Bridge",
    "domain": "Agent interoperability",
    "role": "Task handoffs",
    "perspective": "Define interoperable task exchange, capabilities and delegated work.",
    "group": "integration",
    "palette_token": "DSW-MO-P02",
    "fallback_hex": "#00C0F6",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 82,
    "identity_code": "DSW-MO-082",
    "agent_id": "agent-acp",
    "display_name": "Mint Workbench",
    "domain": "Editor integration",
    "role": "Agent-client sessions",
    "perspective": "Align agent sessions, editor events and user-visible tool interaction.",
    "group": "integration",
    "palette_token": "DSW-MO-P03",
    "fallback_hex": "#00B0ED",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 83,
    "identity_code": "DSW-MO-083",
    "agent_id": "agent-identity",
    "display_name": "Mint Passport",
    "domain": "Agent identity",
    "role": "Identity and credentials",
    "perspective": "Map principals, credentials and capability grants with explicit ownership.",
    "group": "trust",
    "palette_token": "DSW-MO-P04",
    "fallback_hex": "#00A1E3",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 84,
    "identity_code": "DSW-MO-084",
    "agent_id": "agent-policy",
    "display_name": "Mint Charter",
    "domain": "Policy engineering",
    "role": "Bounded authority",
    "perspective": "Specify permitted actions, escalation paths and policy evaluation evidence.",
    "group": "trust",
    "palette_token": "DSW-MO-P05",
    "fallback_hex": "#0092DA",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 85,
    "identity_code": "DSW-MO-085",
    "agent_id": "agent-memory",
    "display_name": "Mint Recall",
    "domain": "Persistent memory",
    "role": "Memory engineering",
    "perspective": "Manage memory scope, retrieval, expiry and provenance.",
    "group": "knowledge",
    "palette_token": "DSW-MO-P06",
    "fallback_hex": "#0083D1",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 86,
    "identity_code": "DSW-MO-086",
    "agent_id": "agent-ontology",
    "display_name": "Mint Atlas",
    "domain": "Ontology engineering",
    "role": "Semantic modeling",
    "perspective": "Define concepts, relationships and interoperable meaning boundaries.",
    "group": "knowledge",
    "palette_token": "DSW-MO-P07",
    "fallback_hex": "#0074C7",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 87,
    "identity_code": "DSW-MO-087",
    "agent_id": "agent-knowledge-graph",
    "display_name": "Mint Lattice",
    "domain": "Knowledge graphs",
    "role": "Relationship reasoning",
    "perspective": "Build typed relationships, graph queries and evidence-linked traversals.",
    "group": "knowledge",
    "palette_token": "DSW-MO-P08",
    "fallback_hex": "#0066BE",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 88,
    "identity_code": "DSW-MO-088",
    "agent_id": "agent-retrieval",
    "display_name": "Mint Seek",
    "domain": "Grounded retrieval",
    "role": "Evidence retrieval",
    "perspective": "Select context through hybrid retrieval and explicit source attribution.",
    "group": "knowledge",
    "palette_token": "DSW-MO-P09",
    "fallback_hex": "#0056B5",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 89,
    "identity_code": "DSW-MO-089",
    "agent_id": "agent-reranking",
    "display_name": "Mint Rank",
    "domain": "Relevance ranking",
    "role": "Result ordering",
    "perspective": "Evaluate candidate evidence and tune task-specific result ordering.",
    "group": "knowledge",
    "palette_token": "DSW-MO-P10",
    "fallback_hex": "#0047AB",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 90,
    "identity_code": "DSW-MO-090",
    "agent_id": "agent-embeddings",
    "display_name": "Mint Vector",
    "domain": "Embedding systems",
    "role": "Vector representation",
    "perspective": "Compare embeddings, similarity behavior and vector index configuration.",
    "group": "knowledge",
    "palette_token": "DSW-MO-P11",
    "fallback_hex": "#394AB0",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 91,
    "identity_code": "DSW-MO-091",
    "agent_id": "agent-context",
    "display_name": "Mint Context",
    "domain": "Context engineering",
    "role": "Context composition",
    "perspective": "Budget, compress and route relevant context without losing provenance.",
    "group": "knowledge",
    "palette_token": "DSW-MO-P12",
    "fallback_hex": "#574BB4",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 92,
    "identity_code": "DSW-MO-092",
    "agent_id": "agent-schemas",
    "display_name": "Mint Schema",
    "domain": "Schema design",
    "role": "Contract evolution",
    "perspective": "Define typed schemas, migrations and version-compatible payloads.",
    "group": "engineering",
    "palette_token": "DSW-MO-P13",
    "fallback_hex": "#714CB9",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 93,
    "identity_code": "DSW-MO-093",
    "agent_id": "agent-provenance",
    "display_name": "Mint Ledger",
    "domain": "Evidence provenance",
    "role": "Lineage and attribution",
    "perspective": "Track artifact lineage, source attribution and evidence dependencies.",
    "group": "trust",
    "palette_token": "DSW-MO-P14",
    "fallback_hex": "#894ABE",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 94,
    "identity_code": "DSW-MO-094",
    "agent_id": "agent-evaluation",
    "display_name": "Mint Bench",
    "domain": "Agent evaluation",
    "role": "Benchmark design",
    "perspective": "Design repeatable tasks, scoring criteria and regression analysis.",
    "group": "assurance",
    "palette_token": "DSW-MO-P15",
    "fallback_hex": "#A147C2",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 95,
    "identity_code": "DSW-MO-095",
    "agent_id": "agent-observability",
    "display_name": "Mint Trace",
    "domain": "Agent observability",
    "role": "Execution telemetry",
    "perspective": "Correlate traces, events, costs and tool outcomes.",
    "group": "assurance",
    "palette_token": "DSW-MO-P16",
    "fallback_hex": "#B942C7",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 96,
    "identity_code": "DSW-MO-096",
    "agent_id": "agent-routing",
    "display_name": "Mint Switch",
    "domain": "Model routing",
    "role": "Capability selection",
    "perspective": "Route tasks across providers by declared capability, budget and policy.",
    "group": "orchestration",
    "palette_token": "DSW-MO-P17",
    "fallback_hex": "#D039CB",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 97,
    "identity_code": "DSW-MO-097",
    "agent_id": "agent-planning",
    "display_name": "Mint Compass",
    "domain": "Task planning",
    "role": "Dependency decomposition",
    "perspective": "Decompose goals into bounded tasks, dependencies and acceptance checks.",
    "group": "orchestration",
    "palette_token": "DSW-MO-P18",
    "fallback_hex": "#E72AD0",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 98,
    "identity_code": "DSW-MO-098",
    "agent_id": "agent-scheduler",
    "display_name": "Mint Cadence",
    "domain": "Scheduling",
    "role": "Fair execution",
    "perspective": "Schedule work with quotas, cancellation and resource-aware fairness.",
    "group": "orchestration",
    "palette_token": "DSW-MO-P19",
    "fallback_hex": "#FF00D4",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 99,
    "identity_code": "DSW-MO-099",
    "agent_id": "agent-replay",
    "display_name": "Mint Replay",
    "domain": "Execution replay",
    "role": "Reproducible sessions",
    "perspective": "Capture replay inputs, event order and reproducibility constraints.",
    "group": "assurance",
    "palette_token": "DSW-MO-P20",
    "fallback_hex": "#FE24C4",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 100,
    "identity_code": "DSW-MO-100",
    "agent_id": "agent-sandbox",
    "display_name": "Mint Capsule",
    "domain": "Runtime isolation",
    "role": "Execution boundaries",
    "perspective": "Define process isolation, resource limits and artifact boundaries.",
    "group": "platform",
    "palette_token": "DSW-MO-P21",
    "fallback_hex": "#FE34B4",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 101,
    "identity_code": "DSW-MO-101",
    "agent_id": "agent-browser",
    "display_name": "Mint Scout",
    "domain": "Browser automation",
    "role": "Web interaction",
    "perspective": "Navigate page state, interaction targets and browser session evidence.",
    "group": "interaction",
    "palette_token": "DSW-MO-P22",
    "fallback_hex": "#FE3EA3",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 102,
    "identity_code": "DSW-MO-102",
    "agent_id": "agent-terminal",
    "display_name": "Mint Shell",
    "domain": "Terminal operations",
    "role": "Command workflows",
    "perspective": "Plan scoped commands, capture results and manage process lifecycles.",
    "group": "interaction",
    "palette_token": "DSW-MO-P23",
    "fallback_hex": "#FE4692",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 103,
    "identity_code": "DSW-MO-103",
    "agent_id": "agent-filesystem",
    "display_name": "Mint Vault",
    "domain": "File operations",
    "role": "Workspace integrity",
    "perspective": "Organize workspaces, atomic writes, diffs and artifact provenance.",
    "group": "platform",
    "palette_token": "DSW-MO-P24",
    "fallback_hex": "#FE4C80",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 104,
    "identity_code": "DSW-MO-104",
    "agent_id": "agent-network",
    "display_name": "Mint Packet",
    "domain": "Network architecture",
    "role": "Traffic and topology",
    "perspective": "Inspect topology, traffic paths and connectivity assumptions.",
    "group": "platform",
    "palette_token": "DSW-MO-P25",
    "fallback_hex": "#FE516D",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 105,
    "identity_code": "DSW-MO-105",
    "agent_id": "agent-storage",
    "display_name": "Mint Archive",
    "domain": "Storage engineering",
    "role": "Durability and capacity",
    "perspective": "Plan storage layouts, durability, capacity and data lifecycle.",
    "group": "platform",
    "palette_token": "DSW-MO-P26",
    "fallback_hex": "#FE5557",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 106,
    "identity_code": "DSW-MO-106",
    "agent_id": "agent-inference",
    "display_name": "Mint Core",
    "domain": "Inference systems",
    "role": "Serving optimization",
    "perspective": "Compare serving configurations, latency budgets and throughput.",
    "group": "learning",
    "palette_token": "DSW-MO-P27",
    "fallback_hex": "#FF583C",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 107,
    "identity_code": "DSW-MO-107",
    "agent_id": "agent-quantization",
    "display_name": "Mint Bit",
    "domain": "Quantization",
    "role": "Efficient representations",
    "perspective": "Evaluate numerical precision, compression and quality tradeoffs.",
    "group": "learning",
    "palette_token": "DSW-MO-P28",
    "fallback_hex": "#FF5A00",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 108,
    "identity_code": "DSW-MO-108",
    "agent_id": "agent-training",
    "display_name": "Mint Learn",
    "domain": "Model training",
    "role": "Training pipelines",
    "perspective": "Track data preparation, training configuration and evaluation artifacts.",
    "group": "learning",
    "palette_token": "DSW-MO-P29",
    "fallback_hex": "#F85402",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 109,
    "identity_code": "DSW-MO-109",
    "agent_id": "agent-reinforcement",
    "display_name": "Mint Reward",
    "domain": "Reinforcement learning",
    "role": "Reward and policy design",
    "perspective": "Define rewards, environments and repeatable policy evaluation.",
    "group": "learning",
    "palette_token": "DSW-MO-P30",
    "fallback_hex": "#F24E04",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 110,
    "identity_code": "DSW-MO-110",
    "agent_id": "agent-vision",
    "display_name": "Mint Lens",
    "domain": "Computer vision",
    "role": "Visual understanding",
    "perspective": "Interpret visual evidence with spatial alignment and confidence.",
    "group": "perception",
    "palette_token": "DSW-MO-P31",
    "fallback_hex": "#EC4705",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 111,
    "identity_code": "DSW-MO-111",
    "agent_id": "agent-ocr",
    "display_name": "Mint Read",
    "domain": "Document recognition",
    "role": "Text and layout",
    "perspective": "Bind recognized text to layout, coordinates and reading order.",
    "group": "perception",
    "palette_token": "DSW-MO-P32",
    "fallback_hex": "#E54107",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 112,
    "identity_code": "DSW-MO-112",
    "agent_id": "agent-speech",
    "display_name": "Mint Voice",
    "domain": "Speech systems",
    "role": "Audio interaction",
    "perspective": "Coordinate transcription, speech output and time-aligned audio evidence.",
    "group": "perception",
    "palette_token": "DSW-MO-P33",
    "fallback_hex": "#DF3A08",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 113,
    "identity_code": "DSW-MO-113",
    "agent_id": "agent-robotics",
    "display_name": "Mint Motion",
    "domain": "Robotics",
    "role": "Embodied action",
    "perspective": "Model sensing, motion constraints and testable action plans.",
    "group": "physical",
    "palette_token": "DSW-MO-P34",
    "fallback_hex": "#D83309",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 114,
    "identity_code": "DSW-MO-114",
    "agent_id": "agent-simulation",
    "display_name": "Mint Twin",
    "domain": "Simulation",
    "role": "Virtual validation",
    "perspective": "Build reproducible scenarios and compare simulated outcomes.",
    "group": "physical",
    "palette_token": "DSW-MO-P35",
    "fallback_hex": "#D22C0A",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 115,
    "identity_code": "DSW-MO-115",
    "agent_id": "agent-geospatial",
    "display_name": "Mint Terrain",
    "domain": "Geospatial systems",
    "role": "Spatial reasoning",
    "perspective": "Handle coordinate systems, spatial queries and map-linked evidence.",
    "group": "physical",
    "palette_token": "DSW-MO-P36",
    "fallback_hex": "#CB230A",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 116,
    "identity_code": "DSW-MO-116",
    "agent_id": "agent-api-design",
    "display_name": "Mint Interface",
    "domain": "API architecture",
    "role": "Interface design",
    "perspective": "Define API resources, error contracts and version boundaries.",
    "group": "engineering",
    "palette_token": "DSW-MO-P37",
    "fallback_hex": "#C51A0B",
    "material_kind": "solid",
    "material_strength": 0
  },
  {
    "swarm_index": 117,
    "identity_code": "DSW-MO-117",
    "agent_id": "agent-data-quality",
    "display_name": "Mint Clean",
    "domain": "Data quality",
    "role": "Validation and repair",
    "perspective": "Check completeness, consistency, duplication and repair provenance.",
    "group": "data",
    "palette_token": "DSW-MO-P38",
    "fallback_hex": "#C33F2B",
    "material_kind": "opal-splatter",
    "material_strength": 0.11111111
  },
  {
    "swarm_index": 118,
    "identity_code": "DSW-MO-118",
    "agent_id": "agent-etl",
    "display_name": "Mint Channel",
    "domain": "Data pipelines",
    "role": "Data transformation",
    "perspective": "Map source-to-target transformations and trace pipeline lineage.",
    "group": "data",
    "palette_token": "DSW-MO-P39",
    "fallback_hex": "#C05841",
    "material_kind": "opal-splatter",
    "material_strength": 0.22222222
  },
  {
    "swarm_index": 119,
    "identity_code": "DSW-MO-119",
    "agent_id": "agent-event-streams",
    "display_name": "Mint Pulse",
    "domain": "Event streaming",
    "role": "Event contracts",
    "perspective": "Define event schemas, ordering, idempotency and replay behavior.",
    "group": "data",
    "palette_token": "DSW-MO-P40",
    "fallback_hex": "#BB6C54",
    "material_kind": "opal-splatter",
    "material_strength": 0.33333333
  },
  {
    "swarm_index": 120,
    "identity_code": "DSW-MO-120",
    "agent_id": "agent-ui-design",
    "display_name": "Mint Canvas",
    "domain": "Interface design",
    "role": "Visual systems",
    "perspective": "Translate interaction requirements into coherent layouts and design tokens.",
    "group": "creation",
    "palette_token": "DSW-MO-P41",
    "fallback_hex": "#B57E67",
    "material_kind": "opal-splatter",
    "material_strength": 0.44444444
  },
  {
    "swarm_index": 121,
    "identity_code": "DSW-MO-121",
    "agent_id": "agent-accessibility",
    "display_name": "Mint Access",
    "domain": "Accessibility",
    "role": "Inclusive interaction",
    "perspective": "Review keyboard behavior, readable contrast and accessible semantics.",
    "group": "creation",
    "palette_token": "DSW-MO-P42",
    "fallback_hex": "#AD8F79",
    "material_kind": "opal-splatter",
    "material_strength": 0.55555556
  },
  {
    "swarm_index": 122,
    "identity_code": "DSW-MO-122",
    "agent_id": "agent-documentation",
    "display_name": "Mint Scribe",
    "domain": "Technical writing",
    "role": "Knowledge communication",
    "perspective": "Produce accurate, structured documentation and explicit examples.",
    "group": "creation",
    "palette_token": "DSW-MO-P43",
    "fallback_hex": "#A2A08B",
    "material_kind": "opal-splatter",
    "material_strength": 0.66666667
  },
  {
    "swarm_index": 123,
    "identity_code": "DSW-MO-123",
    "agent_id": "agent-research",
    "display_name": "Mint Inquiry",
    "domain": "Research methods",
    "role": "Evidence synthesis",
    "perspective": "Frame questions, compare evidence and track uncertainty.",
    "group": "creation",
    "palette_token": "DSW-MO-P44",
    "fallback_hex": "#95B09D",
    "material_kind": "opal-splatter",
    "material_strength": 0.77777778
  },
  {
    "swarm_index": 124,
    "identity_code": "DSW-MO-124",
    "agent_id": "agent-privacy",
    "display_name": "Mint Veil",
    "domain": "Privacy engineering",
    "role": "Data minimization",
    "perspective": "Scope collection, retention and disclosure of sensitive data.",
    "group": "trust",
    "palette_token": "DSW-MO-P45",
    "fallback_hex": "#83C0B0",
    "material_kind": "opal-splatter",
    "material_strength": 0.88888889
  },
  {
    "swarm_index": 125,
    "identity_code": "DSW-MO-125",
    "agent_id": "agent-threat-modeling",
    "display_name": "Mint Shield",
    "domain": "Threat modeling",
    "role": "Security analysis",
    "perspective": "Map trust boundaries, plausible abuse paths and mitigations.",
    "group": "trust",
    "palette_token": "DSW-MO-P46",
    "fallback_hex": "#69CFC2",
    "material_kind": "opal-splatter",
    "material_strength": 1.0
  },
  {
    "swarm_index": 126,
    "identity_code": "DSW-MO-126",
    "agent_id": "agent-formal-verification",
    "display_name": "Mint Proof",
    "domain": "Formal methods",
    "role": "Invariant checking",
    "perspective": "Define invariants and analyze properties against explicit assumptions.",
    "group": "assurance",
    "palette_token": "DSW-MO-P47",
    "fallback_hex": "#67D2C2",
    "material_kind": "opal-splatter",
    "material_strength": 0.88888889
  },
  {
    "swarm_index": 127,
    "identity_code": "DSW-MO-127",
    "agent_id": "agent-sustainability",
    "display_name": "Mint Balance",
    "domain": "Resource efficiency",
    "role": "Sustainable operations",
    "perspective": "Measure energy, utilization and resource tradeoffs against workloads.",
    "group": "physical",
    "palette_token": "DSW-MO-P48",
    "fallback_hex": "#65D4C2",
    "material_kind": "opal-splatter",
    "material_strength": 0.77777778
  },
  {
    "swarm_index": 128,
    "identity_code": "DSW-MO-128",
    "agent_id": "agent-swarm-coordination",
    "display_name": "Mint Taproot",
    "domain": "Swarm coordination",
    "role": "Bounded orchestration",
    "perspective": "Coordinate perspectives, budgets, dependencies and reviewable outcomes.",
    "group": "orchestration",
    "palette_token": "DSW-MO-P49",
    "fallback_hex": "#62D7C2",
    "material_kind": "opal-splatter",
    "material_strength": 0.66666667
  }
] as const;
export type MintOpalAgentId = typeof mintOpalAgents[number]["agent_id"];
export function findMintOpalAgent(id: MintOpalAgentId) { return mintOpalAgents.find(a => a.agent_id === id)!; }
