// Generated identity registry. Solid fallback colors only.
namespace Darbot.Swarm;
public static class MintOpalPalette
{
    public static readonly System.Collections.Generic.IReadOnlyDictionary<string, uint> Argb =
        new System.Collections.Generic.Dictionary<string, uint>
        {
            ["agent-adk"] = 0xFF60D9C2u,
            ["agent-ag2"] = 0xFF5DDCC2u,
            ["agent-agno"] = 0xFF5ADEC2u,
            ["agent-bot"] = 0xFF57E1C2u,
            ["agent-claude-sdk"] = 0xFF54E3C2u,
            ["agent-computer"] = 0xFF50E6C2u,
            ["agent-crewai"] = 0xFF6BE9C9u,
            ["agent-langgraph"] = 0xFF81EBCFu,
            ["agent-langgraph-agui"] = 0xFF95EED6u,
            ["agent-langroid"] = 0xFFA6F0DDu,
            ["agent-llamaindex"] = 0xFFB7F3E4u,
            ["agent-mastra"] = 0xFFC7F5EAu,
            ["agent-microsoft"] = 0xFFD6F7F1u,
            ["agent-pydantic-ai"] = 0xFFE5F9F8u,
            ["agent-strands"] = 0xFFF4FBFFu,
            ["agent-mcp"] = 0xFF00CFFFu,
            ["agent-a2a"] = 0xFF00C0F6u,
            ["agent-acp"] = 0xFF00B0EDu,
            ["agent-identity"] = 0xFF00A1E3u,
            ["agent-policy"] = 0xFF0092DAu,
            ["agent-memory"] = 0xFF0083D1u,
            ["agent-ontology"] = 0xFF0074C7u,
            ["agent-knowledge-graph"] = 0xFF0066BEu,
            ["agent-retrieval"] = 0xFF0056B5u,
            ["agent-reranking"] = 0xFF0047ABu,
            ["agent-embeddings"] = 0xFF394AB0u,
            ["agent-context"] = 0xFF574BB4u,
            ["agent-schemas"] = 0xFF714CB9u,
            ["agent-provenance"] = 0xFF894ABEu,
            ["agent-evaluation"] = 0xFFA147C2u,
            ["agent-observability"] = 0xFFB942C7u,
            ["agent-routing"] = 0xFFD039CBu,
            ["agent-planning"] = 0xFFE72AD0u,
            ["agent-scheduler"] = 0xFFFF00D4u,
            ["agent-replay"] = 0xFFFE24C4u,
            ["agent-sandbox"] = 0xFFFE34B4u,
            ["agent-browser"] = 0xFFFE3EA3u,
            ["agent-terminal"] = 0xFFFE4692u,
            ["agent-filesystem"] = 0xFFFE4C80u,
            ["agent-network"] = 0xFFFE516Du,
            ["agent-storage"] = 0xFFFE5557u,
            ["agent-inference"] = 0xFFFF583Cu,
            ["agent-quantization"] = 0xFFFF5A00u,
            ["agent-training"] = 0xFFF85402u,
            ["agent-reinforcement"] = 0xFFF24E04u,
            ["agent-vision"] = 0xFFEC4705u,
            ["agent-ocr"] = 0xFFE54107u,
            ["agent-speech"] = 0xFFDF3A08u,
            ["agent-robotics"] = 0xFFD83309u,
            ["agent-simulation"] = 0xFFD22C0Au,
            ["agent-geospatial"] = 0xFFCB230Au,
            ["agent-api-design"] = 0xFFC51A0Bu,
            ["agent-data-quality"] = 0xFFC33F2Bu,
            ["agent-etl"] = 0xFFC05841u,
            ["agent-event-streams"] = 0xFFBB6C54u,
            ["agent-ui-design"] = 0xFFB57E67u,
            ["agent-accessibility"] = 0xFFAD8F79u,
            ["agent-documentation"] = 0xFFA2A08Bu,
            ["agent-research"] = 0xFF95B09Du,
            ["agent-privacy"] = 0xFF83C0B0u,
            ["agent-threat-modeling"] = 0xFF69CFC2u,
            ["agent-formal-verification"] = 0xFF67D2C2u,
            ["agent-sustainability"] = 0xFF65D4C2u,
            ["agent-swarm-coordination"] = 0xFF62D7C2u,
        };
}